version: '3'
services:
  db:
    image: 'postgres:latest'
    ports:
      - '4111:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db

  # api:
  #   build:
  #     context: ./
  #     dockerfile: Dockerfile
  #   environment:
  #     DB_DIALECT: postgres
  #     DB_HOST: db
  #     DB_PORT: 5432
  #     DB_USERNAME: postgres
  #     DB_PASSWORD: password
  #     DB_DATABASE: db
  #   depends_on:
  #     db:
  #       condition: service_healthy  # Wait for the database service to be healthy

#  test-db:
#    image: 'postgres:latest'
#    ports:
#      - '5434:5432'
#    environment:
#      POSTGRES_PASSWORD: password
#      POSTGRES_USER: user
#      POSTGRES_DB: test_db
#    healthcheck:
#      test: ["CMD-SHELL", "pg_isready -U user"]
#      interval: 30s
#      timeout: 5s
#      retries: 3
#
#
